version: "3.9"

services:
  beelzebub:
    build: .
    #network_mode: host # Not work on Mac OS
    container_name: beelzebub
    restart: always
    ports: # Remove me, if use configuration network_mode: host
      - "22:22"
      - "8080:8080"
      - "80:80"
    environment:
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'